In [3]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("../data/complaints_clean.csv")

print(df.shape)
print(df.head())

(577, 9)
   complaint_id      category  \
0             1  Water Supply
1             2   Road Damage
2             3  Street Light
3             4  Water Supply
4             5  Street Light

                                      complaint_text         area  \
0  Irregular water supply timing in Melapudur, wa...    Melapudur
1  Deep crack across the road in Cantonment is wi...   Cantonment
2  Broken street light glass in Anna Nagar Lake R...   Anna Nagar
3  Irregular water supply timing in Golden Rock, ...  Golden Rock
4  Street light near Woraiyur bus stop flickers c...     Woraiyur

  date_reported priority       status  \
0    2026-03-11     High  In Progress
1    2026-02-14   Medium  In Progress
2    2025-05-16     High  In Progress
3    2025-04-29   Medium     Resolved
4    2025-12-05      Low     Resolved

                                          clean_text  \
0  irregular water supply timing melapudur water ...
1  deep crack across road cantonment widening eve...
2  broken street light glass anna nagar lake road...
3  irregular water supply timing golden rock wate...
4  street light near woraiyur bus stop flickers c...

                                              tokens
0  ['irregular', 'water', 'supply', 'timing', 'me...
1  ['deep', 'crack', 'across', 'road', 'cantonmen...
2  ['broken', 'street', 'light', 'glass', 'anna',...
3  ['irregular', 'water', 'supply', 'timing', 'go...
4  ['street', 'light', 'near', 'woraiyur', 'bus',...

In [4]:
print(df.isnull().sum())

complaint_id      0
category          0
complaint_text    0
area              0
date_reported     0
priority          0
status            0
clean_text        0
tokens            0
dtype: int64

In [5]:
# Input feature
X = df["clean_text"]

# Target label
y = df["category"]

print("Input (X):")
print(X.head())

print("\nTarget (y):")
print(y.head())

Input (X):
0    irregular water supply timing melapudur water ...
1    deep crack across road cantonment widening eve...
2    broken street light glass anna nagar lake road...
3    irregular water supply timing golden rock wate...
4    street light near woraiyur bus stop flickers c...
Name: clean_text, dtype: str

Target (y):
0    Water Supply
1     Road Damage
2    Street Light
3    Water Supply
4    Street Light
Name: category, dtype: str

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF Vectorizer
vectorizer = TfidfVectorizer(
    max_features=1000,
    stop_words="english"
)

# Convert text into numerical features
X_features = vectorizer.fit_transform(X)

# Print shape
print("TF-IDF Matrix Shape:", X_features.shape)

TF-IDF Matrix Shape: (577, 248)

In [7]:
print(vectorizer.get_feature_names_out()[:20])

['accidents' 'ago' 'animal' 'anna' 'appliances' 'ariyamangalam' 'arrived'
 'attracting' 'bad' 'bharathi' 'bin' 'blocked' 'blocking' 'booking' 'box'
 'breaker' 'breeding' 'broken' 'bus' 'bypass']

In [8]:
from sklearn.preprocessing import LabelEncoder

# Create Label Encoder
label_encoder = LabelEncoder()

# Convert categories into numbers
y_encoded = label_encoder.fit_transform(y)

# Print encoded labels
print("Encoded Labels:")
print(y_encoded[:10])

Encoded Labels:
[5 3 4 5 4 2 0 5 3 0]

In [9]:
# Display category to number mapping
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print("Category Mapping:")
print(mapping)

Category Mapping:
{'Drainage': np.int64(0), 'Electricity': np.int64(1), 'Garbage': np.int64(2), 'Road Damage': np.int64(3), 'Street Light': np.int64(4), 'Water Supply': np.int64(5)}

In [10]:
print("TF-IDF Matrix Shape :", X_features.shape)
print("Number of Labels    :", len(y_encoded))
print("Number of Classes   :", len(label_encoder.classes_))
print("Classes             :", label_encoder.classes_)

TF-IDF Matrix Shape : (577, 248)
Number of Labels    : 577
Number of Classes   : 6
Classes             : ['Drainage' 'Electricity' 'Garbage' 'Road Damage' 'Street Light'
 'Water Supply']

In [11]:
# ✅ Day 1 Verification Check
print("1. Rows in original clean_text vs feature matrix match:", X_features.shape[0] == len(y_encoded))
print("2. No missing values in labels:", pd.isnull(y_encoded).sum() == 0)
print("3. Number of classes matches expected categories:", len(label_encoder.classes_) == 6)
print("4. TF-IDF feature matrix is non-empty:", X_features.shape[1] > 0)
print("5. Sample check — first row has non-zero features:", X_features[0].nnz > 0)

print("\nSummary:")
print("TF-IDF Matrix Shape :", X_features.shape)
print("Number of Labels    :", len(y_encoded))
print("Number of Classes   :", len(label_encoder.classes_))
print("Classes             :", list(label_encoder.classes_))

1. Rows in original clean_text vs feature matrix match: True
2. No missing values in labels: True
3. Number of classes matches expected categories: True
4. TF-IDF feature matrix is non-empty: True
5. Sample check — first row has non-zero features: True

Summary:
TF-IDF Matrix Shape : (577, 248)
Number of Labels    : 577
Number of Classes   : 6
Classes             : ['Drainage', 'Electricity', 'Garbage', 'Road Damage', 'Street Light', 'Water Supply']

In [12]:
print("Original dataset rows:", len(df))
print("Rows used in feature engineering:", X_features.shape[0])
print("Difference:", len(df) - X_features.shape[0])

Original dataset rows: 577
Rows used in feature engineering: 577
Difference: 0

In [13]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle
import scipy.sparse

In [14]:
# Save the TF-IDF Vectorizer

import pickle

with open("../models/vectorizer.pkl", "wb") as file:
    pickle.dump(vectorizer, file)

print("✅ Vectorizer saved successfully!")

✅ Vectorizer saved successfully!

In [15]:
import pandas as pd

df = pd.read_csv("../data/complaints_clean.csv")

print(df.shape)

df.head()

(577, 9)

,complaint_id,category,complaint_text,area,date_reported,priority,status,clean_text,tokens
0,1,Water Supply,"Irregular water supply timing in Melapudur, wa...",Melapudur,2026-03-11,High,In Progress,irregular water supply timing melapudur water ...,"['irregular', 'water', 'supply', 'timing', 'me..."
1,2,Road Damage,Deep crack across the road in Cantonment is wi...,Cantonment,2026-02-14,Medium,In Progress,deep crack across road cantonment widening eve...,"['deep', 'crack', 'across', 'road', 'cantonmen..."
2,3,Street Light,Broken street light glass in Anna Nagar Lake R...,Anna Nagar,2025-05-16,High,In Progress,broken street light glass anna nagar lake road...,"['broken', 'street', 'light', 'glass', 'anna',..."
3,4,Water Supply,"Irregular water supply timing in Golden Rock, ...",Golden Rock,2025-04-29,Medium,Resolved,irregular water supply timing golden rock wate...,"['irregular', 'water', 'supply', 'timing', 'go..."
4,5,Street Light,Street light near Woraiyur bus stop flickers c...,Woraiyur,2025-12-05,Low,Resolved,street light near woraiyur bus stop flickers c...,"['street', 'light', 'near', 'woraiyur', 'bus',..."

In [16]:
print(df.columns)

Index(['complaint_id', 'category', 'complaint_text', 'area', 'date_reported',
       'priority', 'status', 'clean_text', 'tokens'],
      dtype='str')

In [17]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   complaint_id    577 non-null    int64
 1   category        577 non-null    str
 2   complaint_text  577 non-null    str
 3   area            577 non-null    str
 4   date_reported   577 non-null    str
 5   priority        577 non-null    str
 6   status          577 non-null    str
 7   clean_text      577 non-null    str
 8   tokens          577 non-null    str
dtypes: int64(1), str(8)
memory usage: 40.7 KB
None

In [18]:
# Create TF-IDF Vectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words="english",
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

In [19]:
# Convert clean text into TF-IDF features

X_features = vectorizer.fit_transform(df["clean_text"])

print("TF-IDF Matrix Shape :", X_features.shape)

TF-IDF Matrix Shape : (577, 730)

In [20]:
feature_names = vectorizer.get_feature_names_out()

print("Total Features :", len(feature_names))
print()
print(feature_names[:20])

Total Features : 730

['accidents' 'accidents twowheelers' 'ago' 'animal' 'animal lying' 'anna'
 'anna nagar' 'appliances' 'ariyamangalam' 'ariyamangalam colony'
 'ariyamangalam cross' 'ariyamangalam main' 'ariyamangalam market'
 'ariyamangalam nd' 'arrived' 'attracting' 'attracting stray' 'bad'
 'bad odour' 'bad smell']

In [21]:
import pickle

with open("../models/vectorizer.pkl", "wb") as file:
    pickle.dump(vectorizer, file)

print("✅ Vectorizer saved successfully!")

✅ Vectorizer saved successfully!

In [22]:
import scipy.sparse

scipy.sparse.save_npz(
    "../models/tfidf_matrix.npz",
    X_features
)

print("✅ TF-IDF Matrix saved successfully!")

✅ TF-IDF Matrix saved successfully!

In [23]:
import scipy.sparse
import pickle

# Load back what you saved
X = scipy.sparse.load_npz("../models/tfidf_matrix.npz")
with open("../models/vectorizer.pkl", "rb") as f:
    tfidf = pickle.load(f)

print("✅ Matrix shape:", X.shape)
print("✅ Vocabulary size:", len(tfidf.get_feature_names_out()))
print("✅ Sample features:", tfidf.get_feature_names_out()[:10])

✅ Matrix shape: (577, 730)
✅ Vocabulary size: 730
✅ Sample features: ['accidents' 'accidents twowheelers' 'ago' 'animal' 'animal lying' 'anna'
 'anna nagar' 'appliances' 'ariyamangalam' 'ariyamangalam colony']

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X_features,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X_features,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [27]:
print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", len(y_train))
print("Testing Labels :", len(y_test))

Training Features : (461, 730)
Testing Features : (116, 730)
Training Labels : 461
Testing Labels : 116

In [28]:
model = MultinomialNB()

model.fit(
    X_train,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [29]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0 4 2 2 2 3 5 0 1 0]

In [30]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy :", accuracy)

print("\nClassification Report\n")

print(
    classification_report(
        y_test,
        y_pred
    )
)

print("\nConfusion Matrix\n")

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

Accuracy : 1.0

Classification Report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116


Confusion Matrix

[[19  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0 19  0  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 20]]

In [31]:
with open("../models/naive_bayes_model.pkl","wb") as file:
    pickle.dump(model,file)

print("Naive Bayes Model Saved!")

Naive Bayes Model Saved!

In [32]:
results = pd.DataFrame({

    "Actual":y_test,

    "Predicted":y_pred

})

results.to_csv(

    "../models/day3_predictions.csv",

    index=False

)

print("Predictions Saved!")

Predictions Saved!

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
log_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_model.fit(X_train, y_train)

print("✅ Logistic Regression Model Trained Successfully!")

✅ Logistic Regression Model Trained Successfully!

In [35]:
log_pred = log_model.predict(X_test)

print(log_pred[:10])

[0 4 2 2 2 3 5 0 1 0]

In [36]:
log_accuracy = accuracy_score(y_test, log_pred)

print("Logistic Regression Accuracy :", log_accuracy)

print("\nClassification Report\n")
print(classification_report(y_test, log_pred))

print("\nConfusion Matrix\n")
print(confusion_matrix(y_test, log_pred))

Logistic Regression Accuracy : 1.0

Classification Report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116


Confusion Matrix

[[19  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0 19  0  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 20]]

In [37]:
with open("../models/logistic_regression_model.pkl", "wb") as file:
    pickle.dump(log_model, file)

print("✅ Logistic Regression Model Saved!")

✅ Logistic Regression Model Saved!

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("✅ Random Forest Model Trained Successfully!")

✅ Random Forest Model Trained Successfully!

In [40]:
rf_pred = rf_model.predict(X_test)

print(rf_pred[:10])

[0 4 2 2 2 3 5 0 1 0]

In [41]:
rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy :", rf_accuracy)

print("\nClassification Report\n")
print(classification_report(y_test, rf_pred))

print("\nConfusion Matrix\n")
print(confusion_matrix(y_test, rf_pred))

Random Forest Accuracy : 1.0

Classification Report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116


Confusion Matrix

[[19  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0 19  0  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 20]]

In [42]:
with open("../models/random_forest_model.pkl", "wb") as file:
    pickle.dump(rf_model, file)

print("✅ Random Forest Model Saved!")

✅ Random Forest Model Saved!

In [43]:
comparison = pd.DataFrame({
    "Model": [
        "Naive Bayes",
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy,
        log_accuracy,
        rf_accuracy
    ]
})

print(comparison)

best_model = comparison.loc[comparison["Accuracy"].idxmax()]

print("\n🏆 Best Model:")
print(best_model)

                 Model  Accuracy
0          Naive Bayes       1.0
1  Logistic Regression       1.0
2        Random Forest       1.0

🏆 Best Model:
Model       Naive Bayes
Accuracy            1.0
Name: 0, dtype: object

In [44]:
best_model_name = comparison.loc[comparison["Accuracy"].idxmax(), "Model"]

print("Best Model :", best_model_name)

Best Model : Naive Bayes

In [46]:
import pickle
import pandas as pd

# 1. Check model loads correctly
with open("../models/naive_bayes_model.pkl", "rb") as f:
    model = pickle.load(f)

print("✅ Model loaded:", model)

# 2. Check predictions file exists and has data
preds = pd.read_csv("../models/day3_predictions.csv")

print(preds.head())
print("Total rows:", len(preds))

✅ Model loaded: MultinomialNB()
   Actual  Predicted
0       0          0
1       4          4
2       2          2
3       2          2
4       2          2
Total rows: 116

# Day 4 - Logistic Regression

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [48]:
# Create Logistic Regression model
log_model = LogisticRegression(max_iter=1000)

# Train model
log_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [49]:
# Predict using Logistic Regression
y_pred_log = log_model.predict(X_test)

In [50]:
accuracy_log = accuracy_score(y_test, y_pred_log)

print("Logistic Regression Accuracy:", accuracy_log)

Logistic Regression Accuracy: 1.0

In [51]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116

In [52]:
import joblib

joblib.dump(log_model, "../models/logistic_regression_model.pkl")

print("✅ Logistic Regression model saved successfully!")

✅ Logistic Regression model saved successfully!

In [53]:
import joblib

loaded_log_model = joblib.load("../models/logistic_regression_model.pkl")

print(loaded_log_model)

LogisticRegression(max_iter=1000)

# Day 5 - Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier

In [55]:
# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [56]:
y_pred_rf = rf_model.predict(X_test)

In [57]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", accuracy_rf)

Random Forest Accuracy: 1.0

In [58]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116

In [59]:
import joblib

joblib.dump(rf_model, "../models/random_forest_model.pkl")

print("✅ Random Forest model saved successfully!")

✅ Random Forest model saved successfully!

In [60]:
loaded_rf_model = joblib.load("../models/random_forest_model.pkl")

print(loaded_rf_model)

RandomForestClassifier(random_state=42)

In [63]:
print("========== Model Comparison ==========")
print(f"Naive Bayes          : {accuracy:.4f}")
print(f"Logistic Regression  : {accuracy_log:.4f}")
print(f"Random Forest        : {accuracy_rf:.4f}")

========== Model Comparison ==========
Naive Bayes          : 1.0000
Logistic Regression  : 1.0000
Random Forest        : 1.0000

In [64]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd

In [65]:
# Train Naive Bayes

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

nb_acc = accuracy_score(y_test, nb_pred)

print("Naive Bayes Accuracy :", nb_acc)

Naive Bayes Accuracy : 1.0

In [66]:
# Train Logistic Regression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

lr_acc = accuracy_score(y_test, lr_pred)

print("Logistic Regression Accuracy :", lr_acc)

Logistic Regression Accuracy : 1.0

In [67]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy :", rf_acc)

Random Forest Accuracy : 1.0

In [68]:
comparison = pd.DataFrame({
    "Model": [
        "Naive Bayes",
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        nb_acc,
        lr_acc,
        rf_acc
    ]
})

comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
)

comparison

                 Model  Accuracy
0          Naive Bayes       1.0
1  Logistic Regression       1.0
2        Random Forest       1.0

In [69]:
best_model = comparison.iloc[0]

print("Best Model :", best_model["Model"])
print("Accuracy :", best_model["Accuracy"])

Best Model : Naive Bayes
Accuracy : 1.0

In [70]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    rf_pred
))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116

In [72]:
comparison.to_csv(
    "../models/model_comparison.csv",
    index=False
)

print("Comparison table saved successfully.")

Comparison table saved successfully.

In [73]:
import joblib

joblib.dump(
    rf_model,
    "../models/best_model.pkl"
)

print("Best model saved successfully.")

Best model saved successfully.

In [76]:
import pandas as pd

print("\nTraining Labels:")
print(pd.Series(y_train).value_counts())

print("\nTesting Labels:")
print(pd.Series(y_test).value_counts())

Training Labels:
4    78
5    77
2    77
0    77
1    76
3    76
Name: count, dtype: int64

Testing Labels:
4    20
5    20
0    19
2    19
3    19
1    19
Name: count, dtype: int64